services:
  # Laravel PHP-FPM
  laravel-app:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /workspace/backend
    volumes:
      - ..:/workspace
      - /workspace/backend/vendor
    networks:
      - app-network
    depends_on:
      - db
      - redis
    env_file:
      - ../backend/.env
    environment:
      - XDEBUG_CONFIG=client_host=host.docker.internal

  # Next.js app
  nextjs-app:
    build:
      context: ../frontend
      dockerfile: ../.devcontainer/docker/frontend/Dockerfile
    container_name: nextjs-app
    working_dir: /workspace/frontend
    volumes:
      - ..:/workspace
      - /workspace/frontend/node_modules
    networks:
      - app-network
    env_file:
      - ../frontend/.env.local
    environment:
      - NODE_ENV=development

  # Nginx web server
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ..:/workspace
      - ./docker/backend/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - laravel-app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - ../backend/.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secret}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # Redis
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 168
      CLUSTER_ID: "UFYEWwZbR3Kfq3naf2ZPMA"
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      app-network:
        aliases:
          - kafka
          - broker

  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
  kafka-data:
